version: '3'
services:
  app:
    build: .
    environment:
      - RAILS_ENV=development
    ports:
      - 3000:3000
    volumes:
      - $PWD:/app
    depends_on:
      - db
      - cache
      - search