version: '3'
services:
  db:
    image: postgres:9
  cache:
    image: memcached
  search:
    image: elasticsearch:5
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
